### ISSUE TITLE
Session 5 - Set up passport services, researcher registers for visas

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/ismb-2022-ga4gh-tutorial#5]
Include tutorial steps to set up the passport service suite, as well as enabling the "researcher" to obtain their passport. Steps include:

- deploy necessary services (passport broker, passport ui node, kratos) (part of docker compose)
- researcher registers
- researcher applies for visas
- admin script gives researcher all (or some) visas

**Comment by emre-f** [comment]
Hey @jb-adams, this issue is mostly complete but I want to clarify two things:

1. There isn't a way for the researcher to "apply" for visas, so I have just added instructions to give visas to the researcher from admin's perspective.
2. Also, currently the instructions are for the admin to give ALL 5 visas to the researcher. Do we want to assign only some of them? (to show what happens if they aren't authenticated etc.)

**Comment by emre-f** [comment]
@yash-puligundla confirmed that she wants all 5 visas added. That is why I will label this issue complete.
